<?php
#AUTOGENERATED BY HYBRIDAUTH 2.2.2 INSTALLER - Friday 1st of August 2014 12:35:35 AM

/**
 * HybridAuth
 * http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
 * (c) 2009-2014, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
 */

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return
    array(/*
        'scn-social-auth' => array(
            "twitterConsumerKey" => "zZI8U5XsIHpgyzKAZNBQZP8NJ",
            "twitterConsumerSecret" => "jfiTIhTbVC78iQzEV9L0LoCiwG3ycOb3fTDslj4WEnjXmGtbzR",

        )*/

	);
